version: "3.9"

services:
  api:
    build: .
    env_file:
      - .env
    ports:
      - "9001:9001"
    networks:
      - rex_shared_network

networks:
  rex_shared_network:
    external: true
    name: rex_shared_network
